### ISSUE TITLE
Probeer gebruik te maken van sections en/of article elementen

### ISSUE THREAD

**Issue by TristanKatte** [Akikosophia/the-startup-responsive-interactieve-website#1]
misschien delen van de content opdelen in meerdere sections

**Comment by Akikosophia** [comment]
Ik heb een article's gebruikt!   

Hieronder even een voorbeeld

<article>
        <div class="separator"></div>
    <h2>Hoe doen we dat?</h2>

    <ul class="list-how-we-do">
      <li>Door snel ideeën te visualiseren en toetsen in de praktijk.</li>
      <li>
        In een sterk veranderende wereld doe je er verstandig aan te
        expliciteren waar je als organisatie voor staat en welke drijfveren je
        deelt met je doelgroep. Vervolgens vertaal je deze waarden
      </li>
      <li>
        En kansen te benutten op basis van waarden- en datagedreven aanpak.
      </li>
      <li>
        Met creatieve en analytische ontwerpers die de mens centraal stellen.
      </li>
      <li>In nauwe samenwerking met jouw team.</li>
    </ul>
    
    <button>Neem contact met ons op</button>


    <img class="photo-men" src="assets/Rectangle 98.jpg" alt="photo-men" />


</article>
