### ISSUE TITLE
Zorg nu weer wel voor een spatie

### ISSUE THREAD

**Issue by saschavanvliett** [Akikosophia/the-startup-responsive-interactieve-website#11]
Er moet een spatie tussen de volgende attributen: 
<img width="191" alt="image" src="https://github.com/Akikosophia/the-startup-responsive-interactieve-website/assets/144007519/f9e55271-b11f-42b6-938b-5cfe5e044342">

**Comment by Akikosophia** [comment]
Bedankt voor je feedback!

Hieronder heb  ik het aangepast
            
<input type="name" id="name" name="user_name" required="name" />

https://github.com/Akikosophia/the-startup-responsive-interactieve-website/blob/83e535cb19f5f36cf9f354227f04201ec57fe895/index.html#L320
