### ISSUE TITLE
Attribuut mag niet op foto

### ISSUE THREAD

**Issue by saschavanvliett** [Akikosophia/the-startup-responsive-interactieve-website#12]
<img width="797" alt="image" src="https://github.com/Akikosophia/the-startup-responsive-interactieve-website/assets/144007519/74969616-ddc7-4db6-b351-8243cca3f0c3">

**Comment by Akikosophia** [comment]
Bedankt voor je feedback :)

Ik heb het aangepast

https://github.com/Akikosophia/the-startup-responsive-interactieve-website/blob/83e535cb19f5f36cf9f354227f04201ec57fe895/index.html#L122-L125

 <img
      class="photo-Susanne-van-Mulken"
      src="assets/image 51.jpg"
      alt="photo-Susanne-van-Mulken">
