### ISSUE TITLE
Root aanmaken

### ISSUE THREAD

**Issue by Daan645** [Akikosophia/the-startup-responsive-interactieve-website#3]
Als je een root aanmaakt kun je makkelijk de fonts, kleuren etc aanpassen. Erg handig als je tussendoor toch iets wilt veranderen.

**Comment by Akikosophia** [comment]
Ik heb de root toegevoegd aan mijn css! 

Hieronder een voorbeeld

:root {
    --primarycolor: #ABCDD9;
    --secondarycolor: white;
    --main-color: #D3E5EB;
    --text-color: 222222;
    --font-size-p: 16px;
    --font-size-h: 32px;
