### ISSUE TITLE
SVG Logo

### ISSUE THREAD

**Issue by dutchcelt** [Akikosophia/the-startup-responsive-interactieve-website#4]
Hier de Informaat logo. Deze SVG heb ik uit de footer van de Informaat website.

```
<svg viewBox="0 0 182 48" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-labelledby="title" role="presentation" class="informaat-logo"><title id="title">Informaat</title> <desc>Het logo van Informaat</desc> <defs><path d="M.00011967 0H47.8698291v47.8697095H.00011967z"></path></defs> <g fill="none" fill-rule="evenodd"><path fill="#333" d="M59.8903919 31.4315504h4.062044V13.6605192h-4.062044zM79.8440126 23.6376736v7.7937871h-3.8080354v-7.2355066c0-1.5740159-.9900054-2.3100127-2.2085887-2.3100127-1.3962996 0-2.3608742.8122891-2.3608742 2.6148829v6.9306364h-3.8080354V18.7379096h3.8080354v1.1931525c.6854344-.9391438 1.9545801-1.5485851 3.6303191-1.5485851 2.5640213 0 4.7471792 1.8277254 4.7471792 5.2551966M87.8659288 18.7379096h2.3611734v3.6557499h-2.3611734v9.0378012h-3.8083346v-9.0378012h-1.7005714v-3.6557499h1.7005714c0-3.5543259 1.9551785-5.6869214 6.169508-5.4329128v3.6557499c-1.4217304-.1268548-2.3611734.304571-2.3611734 1.7771629M101.675801 25.0846552c0-1.8025937-1.269145-2.9957462-2.9194535-2.9957462-1.650009 0-2.9197531 1.1931525-2.9197531 2.9957462 0 1.8025938 1.2697441 2.9957463 2.9197531 2.9957463 1.6503085 0 2.9194535-1.1931525 2.9194535-2.9957463m-9.6469428 0c-.0140617-3.715587 2.9864715-6.7391575 6.7020585-6.7532192 3.7155873-.0140618 6.7391573 2.9867707 6.7532193 6.7020585.013763 3.715587-2.986771 6.7391575-6.7023577 6.7529201-.0083772.0002991-.0167544.0002991-.0254308.0002991-3.6742994.0409885-6.6862016-2.9044946-6.7271901-6.578794-.0005984-.0412876-.0005984-.082276-.0002992-.1232645M115.6636 18.4840207v4.3157535c-1.574016-.2540087-3.808036.3808633-3.808036 2.8943223v5.7374838h-3.808035v-12.693551h3.808035v2.2591511c.507719-1.7008706 2.208589-2.5131597 3.808036-2.5131597M137.648213 23.6376736v7.7937871h-3.808335v-7.4637853c0-1.2694449-.609142-2.081734-1.827725-2.081734-1.269146 0-1.980011.8882823-1.980011 2.3866042v7.1589151h-3.808335v-7.4637853c0-1.2694449-.609142-2.081734-1.827725-2.081734-1.269146 0-1.980011.8882823-1.980011 2.3866042v7.1589151h-3.808334V18.7379096h3.808334v1.1677218c.583711-.8631507 1.700572-1.5231544 3.401741-1.5231544 1.497724 0 2.614883.6094413 3.325748 1.6754399.710866-1.0154362 1.878886-1.6754399 3.681181-1.6754399 2.919454 0 4.823472 2.081734 4.823472 5.2551966M150.264544 25.0846552c0-1.9040177-1.269146-3.0971702-3.021177-3.0971702-1.751433 0-3.020878 1.1931525-3.020878 3.0971702 0 1.9040177 1.269445 3.0974694 3.020878 3.0974694 1.752031 0 3.021177-1.1934517 3.021177-3.0974694zm3.808334-6.3466259v12.693551h-3.808334v-1.1931525c-.83772.9645747-2.081734 1.5482859-3.782605 1.5482859-3.325748 0-6.067485-2.9191547-6.067485-6.7020585 0-3.7826046 2.741737-6.7023577 6.067485-6.7023577 1.700871 0 2.944885.5840105 3.782605 1.5488843v-1.1931525h3.808334zM166.866447 25.0846552c0-1.9040177-1.269145-3.0971702-3.021177-3.0971702-1.751433 0-3.020878 1.1931525-3.020878 3.0971702 0 1.9040177 1.269445 3.0974694 3.020878 3.0974694 1.752032 0 3.021177-1.1934517 3.021177-3.0974694zm3.808335-6.3466259v12.693551h-3.808335v-1.1931525c-.83772.9645747-2.081734 1.5482859-3.782604 1.5482859-3.325748 0-6.067486-2.9191547-6.067486-6.7020585 0-3.7826046 2.741738-6.7023577 6.067486-6.7023577 1.70087 0 2.944884.5840105 3.782604 1.5488843v-1.1931525h3.808335zM179.330553 22.3935997v4.493769c0 1.0914293.939443 1.1928533 2.614883 1.0914293v3.4526028c-4.976057.5080173-6.422919-.9900054-6.422919-4.5440321v-4.493769h-2.031171v-3.6557499h2.031171V16.326114l3.808036-1.1425901v3.5543259h2.614883v3.6557499h-2.614883z"></path> <path fill="#333" d="M33.0550516 35.8498049h-.0011967c-1.9111982-.0592387-3.0995637-1.0782652-3.0995637-2.6615558 0-1.5671346 1.6126108-2.6199691 3.1190107-2.6199691 1.6512058 0 2.9457823 1.1315203 2.9457823 2.576288 0 1.4926373-1.321204 2.7052369-2.9640326 2.7052369zM14.7571544 17.3906466c-1.651505 0-2.9448847-1.1315203-2.9448847-2.5774847 0-1.4917398 1.3200072-2.7052369 2.9448847-2.7052369h.0179511c1.9123949.0592387 3.0995637 1.0794619 3.0995637 2.6630517 0 1.5665363-1.6126109 2.6196699-3.1175148 2.6196699zm2.481446 6.8806724l-.178913 10.5567668-.0110699.6288883-.6285891-.0365006-3.1501261-.1765196-.5573829-.0314145-.0134634-.5570837-.2510168-10.2019327-.0134633-.589695.5884982-.029021 3.5809535-.1777163.6453435-.0314145-.0107707.6456428zm13.3535547-.5849081l.1786138-10.5558693.0110699-.6285891.6273924.0353039 3.1513228.1774171.5561862.0314145.0143609.557383.2504184 10.2016334.0131642.5899942-.5876007.029021-3.5815518.1762204-.644446.0329104.0110699-.6468395zM47.2654741-.00011967L.60447476 1.20888968.00011967 47.2652347l47.86970943.6046543-.604355-47.87000867z"></path></g></svg>
```

**Comment by Akikosophia** [comment]
Ik heb het svg logo toegevoegd aan het bestand  <svg viewBox="0 0 182 48" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-labelledby="title" role="presentation" alt="logo-informaat" class="logo-informaat"><title id="title">Informaat</title> <desc>Het logo van Informaat</desc> <defs><path d="M.00011967 0H47.8698291v47.8697095H.00011967z"></path></defs> <g fill="none" fill-rule="evenodd"><path fill="#333" d="M59.8903919 31.4315504h4.062044V13.6605192h-4.062044zM79.8440126 23.6376736v7.7937871h-3.8080354v-7.2355066c0-1.5740159-.9900054-2.3100127-2.2085887-2.3100127-1.3962996 0-2.3608742.8122891-2.3608742 2.6148829v6.9306364h-3.8080354V18.7379096h3.8080354v1.1931525c.6854344-.9391438 1.9545801-1.5485851 3.6303191-1.5485851 2.5640213 0 4.7471792 1.8277254 4.7471792 5.2551966M87.8659288 18.7379096h2.3611734v3.6557499h-2.3611734v9.0378012h-3.8083346v-9.0378012h-1.7005714v-3.6557499h1.7005714c0-3.5543259 1.9551785-5.6869214 6.169508-5.4329128v3.6557499c-1.4217304-.1268548-2.3611734.304571-2.3611734 1.7771629M101.675801 25.0846552c0-1.8025937-1.269145-2.9957462-2.9194535-2.9957462-1.650009 0-2.9197531 1.1931525-2.9197531 2.9957462 0 1.8025938 1.2697441 2.9957463 2.9197531 2.9957463 1.6503085 0 2.9194535-1.1931525 2.9194535-2.9957463m-9.6469428 0c-.0140617-3.715587 2.9864715-6.7391575 6.7020585-6.7532192 3.7155873-.0140618 6.7391573 2.9867707 6.7532193 6.7020585.013763 3.715587-2.986771 6.7391575-6.7023577 6.7529201-.0083772.0002991-.0167544.0002991-.0254308.0002991-3.6742994.0409885-6.6862016-2.9044946-6.7271901-6.578794-.0005984-.0412876-.0005984-.082276-.0002992-.1232645M115.6636 18.4840207v4.3157535c-1.574016-.2540087-3.808036.3808633-3.808036 2.8943223v5.7374838h-3.808035v-12.693551h3.808035v2.2591511c.507719-1.7008706 2.208589-2.5131597 3.808036-2.5131597M137.648213 23.6376736v7.7937871h-3.808335v-7.4637853c0-1.2694449-.609142-2.081734-1.827725-2.081734-1.269146 0-1.980011.8882823-1.980011 2.3866042v7.1589151h-3.808335v-7.4637853c0-1.2694449-.609142-2.081734-1.827725-2.081734-1.269146 0-1.980011.8882823-1.980011 2.3866042v7.1589151h-3.808334V18.7379096h3.808334v1.1677218c.583711-.8631507 1.700572-1.5231544 3.401741-1.5231544 1.497724 0 2.614883.6094413 3.325748 1.6754399.710866-1.0154362 1.878886-1.6754399 3.681181-1.6754399 2.919454 0 4.823472 2.081734 4.823472 5.2551966M150.264544 25.0846552c0-1.9040177-1.269146-3.0971702-3.021177-3.0971702-1.751433 0-3.020878 1.1931525-3.020878 3.0971702 0 1.9040177 1.269445 3.0974694 3.020878 3.0974694 1.752031 0 3.021177-1.1934517 3.021177-3.0974694zm3.808334-6.3466259v12.693551h-3.808334v-1.1931525c-.83772.9645747-2.081734 1.5482859-3.782605 1.5482859-3.325748 0-6.067485-2.9191547-6.067485-6.7020585 0-3.7826046 2.741737-6.7023577 6.067485-6.7023577 1.700871 0 2.944885.5840105 3.782605 1.5488843v-1.1931525h3.808334zM166.866447 25.0846552c0-1.9040177-1.269145-3.0971702-3.021177-3.0971702-1.751433 0-3.020878 1.1931525-3.020878 3.0971702 0 1.9040177 1.269445 3.0974694 3.020878 3.0974694 1.752032 0 3.021177-1.1934517 3.021177-3.0974694zm3.808335-6.3466259v12.693551h-3.808335v-1.1931525c-.83772.9645747-2.081734 1.5482859-3.782604 1.5482859-3.325748 0-6.067486-2.9191547-6.067486-6.7020585 0-3.7826046 2.741738-6.7023577 6.067486-6.7023577 1.70087 0 2.944884.5840105 3.782604 1.5488843v-1.1931525h3.808335zM179.330553 22.3935997v4.493769c0 1.0914293.939443 1.1928533 2.614883 1.0914293v3.4526028c-4.976057.5080173-6.422919-.9900054-6.422919-4.5440321v-4.493769h-2.031171v-3.6557499h2.031171V16.326114l3.808036-1.1425901v3.5543259h2.614883v3.6557499h-2.614883z"></path> <path fill="#333" d="M33.0550516 35.8498049h-.0011967c-1.9111982-.0592387-3.0995637-1.0782652-3.0995637-2.6615558 0-1.5671346 1.6126108-2.6199691 3.1190107-2.6199691 1.6512058 0 2.9457823 1.1315203 2.9457823 2.576288 0 1.4926373-1.321204 2.7052369-2.9640326 2.7052369zM14.7571544 17.3906466c-1.651505 0-2.9448847-1.1315203-2.9448847-2.5774847 0-1.4917398 1.3200072-2.7052369 2.9448847-2.7052369h.0179511c1.9123949.0592387 3.0995637 1.0794619 3.0995637 2.6630517 0 1.5665363-1.6126109 2.6196699-3.1175148 2.6196699zm2.481446 6.8806724l-.178913 10.5567668-.0110699.6288883-.6285891-.0365006-3.1501261-.1765196-.5573829-.0314145-.0134634-.5570837-.2510168-10.2019327-.0134633-.589695.5884982-.029021 3.5809535-.1777163.6453435-.0314145-.0107707.6456428zm13.3535547-.5849081l.1786138-10.5558693.0110699-.6285891.6273924.0353039 3.1513228.1774171.5561862.0314145.0143609.557383.2504184 10.2016334.0131642.5899942-.5876007.029021-3.5815518.1762204-.644446.0329104.0110699-.6468395zM47.2654741-.00011967L.60447476 1.20888968.00011967 47.2652347l47.86970943.6046543-.604355-47.87000867z"></path></g></svg>

**Comment by Akikosophia** [comment]
Ik heb het logo toegevoegd!

Zie foto 
<img width="1023" alt="Scherm­afbeelding 2024-01-17 om 14 19 26" src="https://github.com/Akikosophia/the-startup-responsive-interactieve-website/assets/144008863/8aab4519-f335-44d9-b2a8-229591e354a1">
