### ISSUE TITLE
Er is geen alt bij de IMG

### ISSUE THREAD

**Issue by Anna-Kyra** [Akikosophia/the-startup-responsive-interactieve-website#6]
```HTML
    <img
      class="photo-Susanne-van-Mulken"
      src="assets/image 51.jpg"
      ="photo-Susanne-van-Mulken">
```
[Permalink](https://github.com/Akikosophia/the-startup-responsive-interactieve-website/blob/b484540c3af37971184ed673b50e538fbb0770ca/index.html#L339-L342)

<img width="1521" alt="Scherm­afbeelding 2024-01-19 om 11 06 40" src="https://github.com/Akikosophia/the-startup-responsive-interactieve-website/assets/144000242/8eff55f6-b493-4b57-bfd1-06ba6c35bc6e">

De` alt` staat er niet

**Comment by Akikosophia** [comment]
Bedankt voor je feedback :)

Ik heb het aangepast

https://github.com/Akikosophia/the-startup-responsive-interactieve-website/blob/83e535cb19f5f36cf9f354227f04201ec57fe895/index.html#L122-L125

 <img
      class="photo-Susanne-van-Mulken"
      src="assets/image 51.jpg"
      alt="photo-Susanne-van-Mulken">
