### ISSUE TITLE
Geen alt bij SVG

### ISSUE THREAD

**Issue by Anna-Kyra** [Akikosophia/the-startup-responsive-interactieve-website#7]
```HTML
    <svg viewBox="0 0 182 48" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-labelledby="title" role="presentation" alt="logo-informaat" class="logo-informaat"><title id="title">Informaat</title>
```

[Permalink](https://github.com/Akikosophia/the-startup-responsive-interactieve-website/blob/b484540c3af37971184ed673b50e538fbb0770ca/index.html#L360)

<img width="1521" alt="Scherm­afbeelding 2024-01-19 om 11 10 08" src="https://github.com/Akikosophia/the-startup-responsive-interactieve-website/assets/144000242/2f176989-c44c-4d9f-b916-e7321de47797">

`Alt` hoort niet bij een `SVG`, maar ik snap dat je het hebt gedaan, want je hebt het waarschijnlijk van hun gekopieërd.

**Comment by Akikosophia** [comment]
Bedankt voor je feedback! :)

Ik heb het aangepast

 https://github.com/Akikosophia/the-startup-responsive-interactieve-website/blob/83e535cb19f5f36cf9f354227f04201ec57fe895/index.html#L367
