### ISSUE TITLE
Spatie bij assets

### ISSUE THREAD

**Issue by saschavanvliett** [Akikosophia/the-startup-responsive-interactieve-website#8]
Je mag geen spatie gebruiken wanneer je iets uit je assets toevoegt. Zie bijgevoegd plaatje:

<img width="214" alt="image" src="https://github.com/Akikosophia/the-startup-responsive-interactieve-website/assets/144007519/69232f66-ce69-452f-8d5a-0652a2ecee78">

**Comment by Akikosophia** [comment]
Bedankt voor je feedback :)

Ik heb het aangepast 

src="assets/HeaderimageExp3.svg"

https://github.com/Akikosophia/the-startup-responsive-interactieve-website/blob/d4a45b7a91f4196b19d4c53989d5bd9ff0248bfe/index.html#L24
